services:
  dev:
    init: true
    #image: compose-bases-void-rust
    image: bardak-plus-dev
    #build:
    #  dockerfile_inline: |
    #    FROM compose-bases-void-rust

    #  additional_contexts:
    #    void-rust: service:void-rust

    volumes:
      - /dev/null:/play/compose.yml:ro
      #- .:/play
      - type: bind
        source: .
        target: /play

    ports:
      - 3030:3030


    working_dir: /play
    stdin_open: true
    tty: true
    command: sleep 999999999
